### ISSUE TITLE
Has the dataset download link changed?

### ISSUE THREAD

**Issue by ban-kexuan** [hbertiche/CLOTH3D#2]
Hello, is the dataset unable to be downloaded? The link cannot be opened...

**Comment by shash29-dev** [comment]
Any update? Please respond!

**Comment by hbertiche** [comment]
Thanks for your interest in our work,

The dataset link has not changed, but the site seems to be down
You should still be able to download the data with these links

Training data is available in a .tar.gz file (~108GB)
http://158.109.8.102/CLOTH3D/Training/train.tar.gz

Validation data is available in two .tar.gz files (~24GB)
http://158.109.8.102/CLOTH3D/Validation/val_t1.tar.gz
http://158.109.8.102/CLOTH3D/Validation/val_t23.tar.gz

Test data is available in two .tar.gz files (~29GB)
http://158.109.8.102/CLOTH3D/Test/test_t1.tar.gz
http://158.109.8.102/CLOTH3D/Test/test_t23.tar.gz

For them to work, right-click and "Save as..."
________________________________
De: Shashikant Verma ***@***.***>
Enviado: sábado, 2 de marzo de 2024 15:32
Para: hbertiche/CLOTH3D ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [hbertiche/CLOTH3D] Has the dataset download link changed? (Issue #2)


Any update? Please respond!
